name: Post Task to Habitica

on:
  issues:
    types: [closed]

jobs:
  notify-external:
    runs-on: ubuntu-latest

    steps:
      - name: Post a completed task to Habitica
        env:
          API_KEY: ${{ secrets.HABITICA_API_KEY }}
          USER_ID: ${{ secrets.HABITICA_USER_ID }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          LABELS_JSON: ${{ toJson(github.event.issue.labels) }}
        run: |
          # Extract effort label and map to value
          LABEL=$(echo "$LABELS_JSON" | jq -r '.[]?.name' | grep -E '^(trivial|easy|medium|hard)' || echo "unknown")

          case "$LABEL" in
            trivial) EFFORT=0.1 ;;
            easy)    EFFORT=1 ;;
            medium)  EFFORT=1.5 ;;
            hard)    EFFORT=2 ;;
            *)       EFFORT=null ;;
          esac

          echo "Detected label: $LABEL"
          echo "Mapped effort: $EFFORT"

          # Parse checklist items from issue body

          CHECKLIST=$(echo "$ISSUE_BODY" | grep -E '^\s*-\s*\[[xX ]\]' | \
            sed -E 's/^\s*-\s*\[x\]\s*(.*)$/{"text":"\1","completed":true}/I' | \
            sed -E 's/^\s*-\s*\[\s\]\s*(.*)$/{"text":"\1","completed":false}/I' | \
            jq -s '.')
          
          # If CHECKLIST is empty, set it to an empty JSON array
          CHECKLIST=${CHECKLIST:-[]}

          echo "Parsed checklist: $CHECKLIST"

          curl -X POST https://habitica.com/api/v3/tasks/user \
            -H "X-Api-Key: $API_KEY" \
            -H "X-Api-User: $USER_ID" \
            -H "X-Client: ${USER_ID}-gh-action" \
            -H "Content-Type: application/json" \
            -d '{
              "text": "'"$ISSUE_TITLE"'",
              "type": "todo",
              "priority": '"$EFFORT"',
              "notes": "GITHUB",
              "checklist": '"$CHECKLIST"'
            }'
